  [overlay]
 color=0x70000000

 [account_management.separator]
 color=0x00000

 [achievement_diary.entry.border]
 color=0x474646
 opacity=150

 [achievement_diary.progress.background]
 color=0x191818
 opacity=255

 [bank.incinerator.border.inner]
 color=0x000000
 opacity=150

 [bank.incinerator.border.outer]
 color=0xf98e6e
 opacity=100

 [bank.inventory.locked]
 color=0x2f2d2d
 opacity=0

 [bank.inventory.rune_pouch.border.inner]
 color=0x000000
 opacity=150

 [bank.inventory.rune_pouch.border.outer]
 color=0xf98e6e
 opacity=100

 [bank.inventory.rune_pouch.loadout.border.inner]
 color=0x000000
 opacity=150

 [bank.inventory.rune_pouch.loadout.border.outer]
 color=0xf98e6e
 opacity=100

 [bank.menu.border.inner]
 color=0x000000
 opacity=150

 [bank.menu.border.inner.dropdown]
 opacity=0

 [bank.menu.border.inner.fillers]
 color=0x000000
 opacity=150

 [bank.menu.border.inner.tab]
 opacity=0

 [bank.menu.border.outer]
 color=0xf98e6e
 opacity=100

 [bank.menu.border.outer.dropdown]
 opacity=0

 [bank.menu.border.outer.fillers]
 color=0xf98e6e
 opacity=0

 [bank.menu.border.outer.tab]
 opacity=0

 [bank.popup.border.inner]
 color=0xf98e6e
 opacity=100

 [bank.popup.border.outer]
 color=0xf98e6e
 opacity=100

 [bank.separator]
 color=0x000000

 [bonds_pouch.border.inner]
 color=0x000000
 opacity=150

 [bonds_pouch.border.outer]
 color=0x000000
 opacity=250

 [bounty_hunter.overlay.background]
 color=0x000000
 opacity=200

 [bounty_hunter.overlay.border.inner]
 color=0x000000

 [bounty_hunter.overlay.border.outer]
 color=0xf98e6e

 [channel_tab.separator]
 color=0x000000

 [chatbox.separator]
 color=0x6D6E7C

 [chatbox.separator.opaque]
 opacity=10

 [chatbox.separator.transparent]
 opacity=200

 [choose_spell.background]
 color=0x000000
 opacity=0

 [choose_spell.border.inner]
 color=0x000000
 opacity=150

 [choose_spell.border.outer]
 color=0xf98e6e
 opacity=100

 [clan_chat.border.inner]
 color=0x000000

 [clan_chat.border.outer]
 color=0xf98e6e

 [clan_chat.border.rectangle]
 color=0xf98e6e

 [collection_log.border]
 color=0x000000

 [colosseum.info.background]
 color=0x000000
 opacity=200

 [colosseum.info.border.inner]
 color=0x000000
 opacity=150

 [colosseum.info.border.outer]
 color=0xf98e6e
 opacity=100

 [colosseum.modifiers.border]
 color=0x000000
 opacity=0

 [colosseum.modifiers.selected]
 color=0xf98e6e
 opacity=0

 [colosseum.tab.border]
 color=0xf98e6e
 opacity=100

 [colosseum.wave.background]
 color=0x000000
 opacity=200

 [colosseum.wave.border.inner]
 color=0x000000
 opacity=150

 [colosseum.wave.border.outer]
 color=0xf98e6e
 opacity=100

 [combat_achievements.boss.border.inner]
 color=0x000000
 opacity=150

 [combat_achievements.boss.border.outer]
 color=0xc26977
 opacity=100

 [combat_achievements.overview.border]
 color=0xc26977
 opacity=100

 [combat_achievements.progress.border.inner]
 color=0x000000
 opacity=150

 [combat_achievements.progress.border.outer]
 color=0xc26977
 opacity=100

 [combat_achievements.rewards.body.border.inner]
 color=0x000000
 opacity=150

 [combat_achievements.rewards.body.border.outer]
 color=0xc26977
 opacity=100

 [combat_achievements.rewards.section.border.inner]
 color=0x000000
 opacity=150

 [combat_achievements.rewards.section.border.outer]
 color=0xc26977
 opacity=100

 [combat_achievements.tasks.dropdown.border.inner]
 color=0x000000
 opacity=150

 [combat_achievements.tasks.dropdown.border.outer]
 color=0xc26977
 opacity=100

 [combat_achievements.tasks.menu.border.inner]
 color=0x000000
 opacity=150

 [combat_achievements.tasks.menu.border.outer]
 color=0xc26977
 opacity=100

 [costumes.border.inner]
 color=0x000000
 opacity=150

 [costumes.border.outer]
 color=0xf98e6e
 opacity=100

 [cox.overlay.background]
 color=0x000000
 opacity=200

 [cox.overlay.border.inner]
 color=0x000000
 opacity=150

 [cox.overlay.border.outer]
 color=0xf98e6e
 opacity=100

 [cox.parties.border.inner]
 color=0x000000
 opacity=150

 [cox.parties.border.outer]
 color=0xf98e6e
 opacity=100

 [cox.party.border.inner]
 color=0x000000
 opacity=150

 [cox.party.border.outer]
 color=0xf98e6e
 opacity=100

 [deposit_box.inventory.border.inner]
 color=0x000000
 opacity=150

 [deposit_box.inventory.border.outer]
 color=0xf98e6e
 opacity=100

 [deposit_box.inventory.locked]
 color=0xf98e6e
 opacity=0

 [deposit_lock.border.inner]
 color=0x000000
 opacity=150

 [deposit_lock.border.outer]
 color=0xf98e6e
 opacity=100

 [deposit_lock.hovered.locked]
 color=0xf98e6e
 opacity=0

 [deposit_lock.hovered.unlocked]
 color=0x040404
 opacity=0

 [deposit_lock.locked]
 color=0xc26977
 opacity=0

 [deposit_lock.unlocked]
 color=0x191818
 opacity=0

 [forestry_kit.body.background]
 color=0x000000
 opacity=200

 [forestry_kit.body.border.inner]
 color=0x000000
 opacity=150

 [forestry_kit.body.border.outer]
 color=0xf98e6e
 opacity=100

 [forestry_kit.info.background]
 color=0x000000
 opacity=200

 [forestry_kit.info.border.inner]
 color=0x000000
 opacity=150

 [forestry_kit.info.border.outer]
 color=0xf98e6e
 opacity=100

 [forestry_shop.body.background]
 color=0x000000
 opacity=200

 [forestry_shop.body.border.inner]
 color=0x000000
 opacity=150

 [forestry_shop.body.border.outer]
 color=0xf98e6e
 opacity=100

 [forestry_shop.dropdown.border.inner]
 color=0x000000
 opacity=150

 [forestry_shop.dropdown.border.outer]
 color=0xf98e6e
 opacity=100

 [forestry_shop.info.background]
 color=0x000000
 opacity=200

 [forestry_shop.info.border.inner]
 color=0x000000
 opacity=150

 [forestry_shop.info.border.outer]
 color=0xf98e6e
 opacity=100

 [forestry_shop.menu.border.inner]
 color=0x000000
 opacity=150

 [forestry_shop.menu.border.outer]
 color=0xf98e6e
 opacity=100

 [forestry_shop.reward.hovered]
 color=0xf98e6e
 opacity=0

 [forestry_shop.reward.selected]
 color=0x000000
 opacity=0

 [friends_chat.border.inner]
 color=0x000000
 opacity=150

 [friends_chat.border.outer]
 color=0xc26977
 opacity=100

 [friends_chat.header.border.inner]
 color=0x000000
 opacity=150

 [friends_chat.header.border.outer]
 color=0xc26977
 opacity=100

 [friends_chat.setup.border.inner]
 color=0x000000
 opacity=150

 [friends_chat.setup.border.outer]
 color=0xc26977
 opacity=100

 [friends_list.header.border.inner]
 color=0x000000
 opacity=150

 [friends_list.header.border.outer]
 color=0xc26977
 opacity=100

 [ge.inventory.glow]
 color=0x979797

 [ge.modify.border.inner]
 color=0x000000
 opacity=0

 [ge.modify.border.outer]
 color=0x000000
 opacity=0

 [ge.offer.border.inner]
 color=0xf98e6e
 opacity=200

 [ge.offer.border.outer]
 color=0x000000
 opacity=255

 [ge.slot.border.inner]
 color=0x000000
 opacity=100

 [ge.slot.border.outer]
 color=0x242222
 opacity=100

 [grouping_tab.border.inner]
 color=0x000000
 opacity=150

 [grouping_tab.border.outer]
 color=0xc26977
 opacity=150

 [grouping_tab.dropdown.border.inner]
 color=0x000000
 opacity=150

 [grouping_tab.dropdown.border.outer]
 color=0xc26977
 opacity=150

 [ignore_list.header.border.inner]
 color=0x000000
 opacity=150

 [ignore_list.header.border.outer]
 color=0xc26977
 opacity=100

 [item_search.background]
 color=0x56547c
 opacity=200

 [item_search.border.inner]
 color=0x000000
 opacity=150

 [item_search.border.outer]
 color=0xc26977
 opacity=100

 [jewellery_box.border.inner]
 color=0x000000
 opacity=150

 [jewellery_box.border.outer]
 color=0xf98e6e
 opacity=100

 [kept_on_death.border.inner]
 color=0x000000
 opacity=150

 [kept_on_death.border.outer]
 color=0xc26977
 opacity=100

 [lectern.border.inner]
 color=0x000000
 opacity=150

 [lectern.border.outer]
 color=0xf98e6e
 opacity=100

 [lms.kda.background]
 color=0x000000
 opacity=100

 [lms.kda.border.inner]
 color=0x000000
 opacity=150

 [lms.kda.border.outer]
 color=0xf98e6e
 opacity=100

 [lms.settings.border.inner]
 color=0x000000
 opacity=150

 [lms.settings.border.outer]
 color=0xf98e6e
 opacity=100

 [lms.shop.border.inner]
 color=0x000000
 opacity=150

 [lms.shop.border.outer]
 color=0xf98e6e
 opacity=100

 [lms.shop.separator]
 color=0xf98e6e
 opacity=100

 [lms.shop.separator.accent]
 color=0x000000
 opacity=150

 [lms.supplies.border.inner]
 color=0x000000
 opacity=150

 [lms.supplies.border.outer]
 color=0xf98e6e
 opacity=100

 [lms.supplies.dropdown.border.inner]
 color=0xf98e6e

 [lms.supplies.dropdown.border.outer]
 color=0x000000

 [lms.supplies.menu.border.inner]
 color=0x000000
 opacity=150

 [lms.supplies.menu.border.outer]
 color=0xf98e6e
 opacity=100

 [looting_bag.border.inner]
 color=0x000000
 opacity=150

 [looting_bag.border.outer]
 color=0xc26977
 opacity=100

 [make_all.background]
 color=0xf98e6e
 opacity=150

 [make_all.quantity]
 color=0xf98e6e
 opacity=150

 [notification.border.inner]
 color=0x000000

 [notification.border.outer]
 color=0xf98e6e

 [other_clan.border.inner]
 color=0x000000
 opacity=150

 [other_clan.border.outer]
 color=0xc26977
 opacity=100

 [pet_house.border.inner]
 color=0x000000
 opacity=150

 [pet_house.border.outer]
 color=0xf98e6e
 opacity=100

 [poh.build_room.border]
 color=0xf98e6e
 opacity=150

 [portal_nexus.border]
 color=0x000000
 opacity=0

 [pvp_arena.confirm_options.separator]
 color=0x000000
 opacity=100

 [pvp_arena.confirm_options.separator.accent]
 color=0xc26977
 opacity=100

 [pvp_arena.duel_options.separator]
 color=0x000000
 opacity=100

 [pvp_arena.recruitment.border.inner]
 color=0x000000
 opacity=150

 [pvp_arena.recruitment.border.outer]
 color=0xc26977
 opacity=100

 [pvp_arena.supplies.kit.dropdown.border.inner]
 color=0x000000
 opacity=150

 [pvp_arena.supplies.kit.dropdown.border.outer]
 color=0xc26977
 opacity=100

 [pvp_arena.supplies.kit.equipment.border.inner]
 color=0x000000
 opacity=150

 [pvp_arena.supplies.kit.equipment.border.outer]
 color=0xc26977
 opacity=100

 [pvp_arena.supplies.kit.inventory.border.inner]
 color=0x000000
 opacity=150

 [pvp_arena.supplies.kit.inventory.border.outer]
 color=0xc26977
 opacity=100

 [pvp_arena.supplies.kit.list.border.inner]
 color=0x000000
 opacity=150

 [pvp_arena.supplies.kit.list.border.outer]
 color=0xc26977
 opacity=100

 [pvp_arena.supplies.kit.menu.border.inner]
 color=0x000000
 opacity=150

 [pvp_arena.supplies.kit.menu.border.outer]
 color=0xc26977
 opacity=100

 [pvp_arena.supplies.separator]
 color=0x000000

 [pvp_arena.supplies.stats.border.inner]
 color=0x000000
 opacity=150

 [pvp_arena.supplies.stats.border.outer]
 color=0xc26977
 opacity=100

 [quest_list.background]
 color=0x000000
 opacity=212

 [quest_tab.separator]
 color=0x000000

 [report.button.hover]
 color=0xc26977

 [rune_pouch.border.inner]
 color=0x000000
 opacity=150

 [rune_pouch.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.boats.other.border.inner]
 color=0x000000
 opacity=150

 [sailing.boats.other.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.boats.other.row.background]
 color=0x222222

 [sailing.boats.other.row.border]
 color=0xf98e6e

 [sailing.boats.recent.background]
 color=0x222222

 [sailing.boats.recent.border.inner]
 color=0x000000
 opacity=150

 [sailing.boats.recent.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.cargo.background]
 color=0x222222
 opacity=0

 [sailing.cargo.border.inner]
 color=0x000000

 [sailing.cargo.border.outer]
 color=0xf98e6e

 [sailing.crew.current.background]
 color=0x222222

 [sailing.crew.current.border.inner]
 color=0x000000
 opacity=150

 [sailing.crew.current.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.crew.help.border.inner]
 color=0x000000
 opacity=150

 [sailing.crew.help.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.crew.recruits.background]
 color=0x222222

 [sailing.crew.recruits.border.inner]
 color=0x000000
 opacity=150

 [sailing.crew.recruits.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.crew.stats.border.inner]
 color=0x000000
 opacity=150

 [sailing.crew.stats.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.customize.body.border]
 color=0xf98e6e
 opacity=50

 [sailing.customize.highlight]
 color=0xf98e6e
 opacity=100

 [sailing.customize.popup.border.inner]
 color=0x000000
 opacity=150

 [sailing.customize.popup.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.customize.row.border]
 color=0xf98e6e

 [sailing.customize.scroll.border.inner]
 color=0x000000
 opacity=150

 [sailing.customize.scroll.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.customize.tab.border]
 color=0xf98e6e
 opacity=100

 [sailing.customize.upgrade.border.inner]
 color=0x000000
 opacity=150

 [sailing.customize.upgrade.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.customize.upgrade.item.background]
 color=0x222222
 opacity=0

 [sailing.log.border]
 color=0xf98e6e
 opacity=100

 [sailing.log.dropdown.border.inner]
 color=0x000000
 opacity=150

 [sailing.log.dropdown.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.log.menu.border.inner]
 color=0x000000
 opacity=150

 [sailing.log.menu.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.tab.assign.background]
 color=0x222222

 [sailing.tab.assign.background.alternate]
 color=0x333333

 [sailing.tab.assign.background.hovered]
 color=0x444444

 [sailing.tab.background]
 color=0x222222
 opacity=0

 [sailing.tab.border.inner]
 color=0x000000
 opacity=150

 [sailing.tab.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.tab.crew.background]
 color=0x222222
 opacity=0

 [sailing.tab.crew.background.alternate]
 color=0x333333
 opacity=0

 [sailing.tab.facilities.divider.inner]
 color=0x000000
 opacity=150

 [sailing.tab.facilities.divider.outer]
 color=0xf98e6e
 opacity=100

 [sailing.tab.facilities.row]
 color=0x444444
 opacity=150

 [sailing.tab.separator]
 color=0xf98e6e

 [sailing.tab.stats.header]
 color=0xf98e6e
 opacity=150

 [sailing.tab.stats.row]
 color=0x444444
 opacity=150

 [sailing.trials.border.inner]
 color=0x000000
 opacity=150

 [sailing.trials.border.outer]
 color=0xf98e6e
 opacity=100

 [sailing.trials.row.background]
 color=0x222222
 opacity=0

 [sailing.trials.row.background.alternate]
 color=0x333333
 opacity=0

 [settings.body.border.inner]
 color=0x000000
 opacity=150

 [settings.body.border.outer]
 color=0xf98e6e
 opacity=100

 [settings.menu.border.inner]
 color=0x000000
 opacity=150

 [settings.menu.border.outer]
 color=0xf98e6e
 opacity=100

 [settings.sidebar.border.inner]
 color=0x000000
 opacity=150

 [settings.sidebar.border.outer]
 color=0xf98e6e
 opacity=100

 [settings_tab.dropdown.border.inner]
 color=0x000000
 opacity=150

 [settings_tab.dropdown.border.outer]
 color=0xf98e6e
 opacity=100

 [settings_tab.menu.border.inner]
 color=0x000000
 opacity=150

 [settings_tab.menu.border.outer]
 color=0xf98e6e
 opacity=100

 [settings_tab.separator]
 color=0x000000

 [skill_guide.body.border.inner]
 color=0x000000
 opacity=150

 [skill_guide.body.border.outer]
 color=0xf98e6e
 opacity=100

 [skill_guide.tab.border]
 color=0x000000
 opacity=0

 [soul_wars.separator.bottom]
 color=0xf98e6e

 [soul_wars.separator.bottom.accent]
 color=0x000000

 [soul_wars.separator.top]
 color=0x000000

 [soul_wars.separator.top.accent]
 color=0xf98e6e

 [spell_tooltip.background]
 color=0x000000
 opacity=150

 [spell_tooltip.border.inner]
 color=0x000000
 opacity=150

 [spell_tooltip.border.outer]
 color=0xc26977
 opacity=100

 [toa.applicants.border.inner]
 color=0x000000
 opacity=150

 [toa.applicants.border.outer]
 color=0xf98e6e
 opacity=150

 [toa.invocations.border.inner]
 color=0x000000
 opacity=150

 [toa.invocations.border.outer]
 color=0xf98e6e
 opacity=150

 [toa.members.border.inner]
 color=0x000000
 opacity=150

 [toa.members.border.outer]
 color=0xf98e6e
 opacity=150

 [toa.parties.border.inner]
 color=0x000000
 opacity=150

 [toa.parties.border.outer]
 color=0xf98e6e
 opacity=150

 [toa.separator.bottom]
 color=0x000000

 [toa.separator.bottom.accent]
 color=0xf98e6e

 [toa.separator.top]
 color=0x000000

 [toa.separator.top.accent]
 color=0xf98e6e

 [toa.summary.border.inner]
 color=0x000000
 opacity=150

 [toa.summary.border.outer]
 color=0xf98e6e
 opacity=150

 [tob.applicants.border.inner]
 color=0x000000
 opacity=150

 [tob.applicants.border.outer]
 color=0xf98e6e
 opacity=100

 [tob.parties.border.inner]
 color=0x000000
 opacity=150

 [tob.parties.border.outer]
 color=0xf98e6e
 opacity=100

 [tob.party.border.inner]
 color=0x000000
 opacity=150

 [tob.party.border.outer]
 color=0xf98e6e
 opacity=100

 [tob.party.header.border.inner]
 color=0x000000
 opacity=150

 [tob.party.header.border.outer]
 color=0xf98e6e
 opacity=100

 [world_map.dropdown.border.inner]
 color=0x000000
 opacity=150

 [world_map.dropdown.border.outer]
 color=0xf98e6e
 opacity=100

 [world_map.key.border.inner]
 color=0x000000
 opacity=150

 [world_map.key.border.outer]
 color=0xf98e6e
 opacity=100

 [world_map.location_menu.border.inner]
 color=0x000000
 opacity=150

 [world_map.location_menu.border.outer]
 color=0xf98e6e
 opacity=100

 [world_map.search.border.inner]
 color=0x000000
 opacity=150

 [world_map.search.border.outer]
 color=0xf98e6e
 opacity=100

 [world_switcher.background]
 color=0x000000

 [world_switcher.border.bottom]
 color=0xf98e6e
 opacity=50

 [world_switcher.border.top]
 color=0xf98e6e
 opacity=50

 [world_switcher.window.border.inner]
 color=0x000000
 opacity=150

 [world_switcher.window.border.outer]
 color=0xf98e6e
 opacity=100

 [xp_tracker.border.inner]
 color=0x000000
 opacity=150

 [xp_tracker.border.outer]
 color=0xf98e6e
 opacity=100