[overlay]
color=0xBC002423

[account_management.separator]
color=0x000000

[achievement_diary.entry.border]
color=0x1c1c1c
opacity=255

[achievement_diary.progress.background]
color=0
opacity=255

[bank.inventory.rune_pouch.border.inner]
color=0x171414
opacity=255

[bank.inventory.rune_pouch.border.outer]
color=0x000000
# opacity=0

[bank.menu.border.inner]
color=0x1b1a18
# opacity=0

[bank.menu.border.outer]
color=0x1b1a18
# opacity=0

[bank.separator]
color=0x1b1a18
# opacity=0

[bonds_pouch.border.inner]
color=0x1b1a18
opacity=255

[bonds_pouch.border.outer]
color=0x000000
# opacity=0

[bounty_hunter.overlay.background]
color=0xBC002423
# opacity=150

[bounty_hunter.overlay.border.inner]
color=0x002c2b

[bounty_hunter.overlay.border.outer]
color=0x001f1f

[channel_tab.separator]
color=0x000000

[chatbox.separator]
color=0x727272
# opacity=0

[choose_spell.background]
color=0x002423
# opacity=0

[choose_spell.border.inner]
color=0x000000
# opacity=0

[choose_spell.border.outer]
color=0x002423
opacity=255

[clan_chat.border.inner]
color=0x1b1a18
opacity=255

[clan_chat.border.outer]
color=0x1b1a18
opacity=255

[colosseum.info.background]
color=0x000000
# opacity=200

[colosseum.info.border.inner]
color=0x18171a
opacity=60

[colosseum.info.border.outer]
color=0x001f1f
# opacity=0

[colosseum.modifiers.border]
color=0x002423
# opacity=0

[colosseum.modifiers.selected]
color=0x000000
# opacity=0

[colosseum.tab.border]
color=0x1b1a18
opacity=255

[colosseum.wave.background]
color=0x000000
# opacity=60

[colosseum.wave.border.inner]
color=0x18171a
opacity=255

[colosseum.wave.border.outer]
color=0x000000
opacity=0

[collection_log.border]
color=0x000000

[combat_achievements.progress.border.inner]
color=0x000000
# opacity=0

[combat_achievements.progress.border.outer]
color=0x1b1a18
opacity=255

[combat_achievements.tasks.menu.border.inner]
color=0x1c1c1c
opacity=255

[combat_achievements.tasks.menu.border.outer]
color=0x000000
# opacity=0

[combat_achievements.tasks.dropdown.border.inner]
color=0x1b1a18
opacity=0

[combat_achievements.tasks.dropdown.border.outer]
color=0x000000
# opacity=0

[combat_achievements.rewards.body.border.inner]
color=0x1b1a18
opacity=255

[combat_achievements.rewards.body.border.outer]
color=0x1b1a18
opacity=255

[combat_achievements.rewards.section.border.inner]
color=0x1b1a18
opacity=255

[combat_achievements.rewards.section.border.outer]
color=0x000000
# opacity=0

[combat_achievements.boss.border.inner]
color=0x000000
# opacity=0

[combat_achievements.boss.border.outer]
color=0x1b1a18
opacity=255

[combat_achievements.overview.border]
color=0x000000
# opacity=0

[costumes.border.inner]
color=0x000000
# opacity=0

[costumes.border.outer]
color=0x1b1a18
opacity=255

[cox.overlay.background]
color=0x002423
opacity=60

[cox.overlay.border.inner]
color=0x002423
# opacity=0

[cox.overlay.border.outer]
color=0x001f1f
opacity=0

[cox.party.border.inner]
color=0x242424
opacity=255

[cox.party.border.outer]
color=0x000000
# opacity=0

[cox.parties.border.inner]
color=0x242424
opacity=255

[cox.parties.border.outer]
color=0x000000
# opacity=0

[forestry_kit.body.background]
color=0x000000
# opacity=200

[forestry_kit.body.border.inner]
color=0x141313
opacity=255

[forestry_kit.body.border.outer]
color=0x000000
# opacity=0

[forestry_kit.info.background]
color=0x000000
# opacity=200

[forestry_kit.info.border.inner]
color=0x121313
opacity=255

[forestry_kit.info.border.outer]
color=0x000000
# opacity=0

[forestry_shop.body.background]
color=0x000000
# opacity=200

[forestry_shop.body.border.inner]
color=0x121313
# opacity=0

[forestry_shop.body.border.outer]
color=0x000000
# opacity=0

[forestry_shop.dropdown.border.inner]
color=0x1b1a18
# opacity=0

[forestry_shop.dropdown.border.outer]
color=0x000000
# opacity=0

[forestry_shop.info.background]
color=0x1b1a18
# opacity=200

[forestry_shop.info.border.inner]
color=0x1b1a18
# opacity=0

[forestry_shop.info.border.outer]
color=0x000000
# opacity=0

[forestry_shop.menu.border.inner]
color=0x1b1a18
# opacity=0

[forestry_shop.menu.border.outer]
color=0x000000
# opacity=0

[friends_chat.border.inner]
color=0x1b1a18
opacity=255

[friends_chat.border.outer]
color=0x1b1a18
opacity=255

[friends_chat.setup.border.inner]
color=0x1b1a18
opacity=255

[friends_chat.setup.border.outer]
color=0x000000
# opacity=0

[friends_chat.header.border.inner]
color=0x1b1a18
opacity=255

[friends_chat.header.border.outer]
color=0x1b1a18
opacity=255

[friends_list.header.border.inner]
color=0x000000
# opacity=0

[friends_list.header.border.outer]
color=0x1c1c1c
# opacity=0

[ge.offer.border.inner]
color=0x1b1a18
opacity=255

[ge.offer.border.outer]
color=0x1b1a18
opacity=255

[ge.slot.border.inner]
color=0x1b1a18
opacity=255

[ge.slot.border.outer]
color=0x1b1a18
opacity=255

[grouping_tab.border.inner]
color=0x1b1819
opacity=255

[grouping_tab.border.outer]
color=0x000000
# opacity=0

[grouping_tab.dropdown.border.inner]
color=0x1b1a18
# opacity=150

[grouping_tab.dropdown.border.outer]
color=0x000000
# opacity=0

[ignore_list.header.border.inner]
color=0x000000
# opacity=0

[ignore_list.header.border.outer]
color=0x1c1c1c
# opacity=0

[item_search.background]
color=0x1469a6
# opacity=200

[item_search.border.inner]
color=0x1469a6
# opacity=150

[item_search.border.outer]
color=0x000000
# opacity=0

[jewellery_box.border.inner]
color=0x1b1a18
opacity=255

[jewellery_box.border.outer]
color=0x1b1a18
opacity=255

[lectern.border.inner]
color=0x1b1a18
opacity=255

[lectern.border.outer]
color=0x1b1a18
opacity=255

[kept_on_death.border.inner]
color=0x000000
# opacity=0

[kept_on_death.border.outer]
color=0x1b1a18
opacity=255

[looting_bag.border.inner]
color=0x18181b
opacity=255

[looting_bag.border.outer]
color=0x000000
# opacity=0

[lms.kda.background]
color=0xBC002423
# opacity=100

[lms.kda.border.inner]
color=0x002423
# opacity=0

[lms.kda.border.outer]
color=0x301934
# opacity=0

[lms.settings.border.inner]
color=0x1c1c1c
opacity=255

[lms.settings.border.outer]
color=0x000000
# opacity=0

[lms.shop.border.inner]
color=0x1c1c1c
opacity=255

[lms.shop.border.outer]
color=0x000000
# opacity=0

[lms.shop.separator]
color=0x1b1a18
opacity=255

[lms.shop.separator.accent]
color=0x000000
opacity=255

[make_all.background]
color=0x53585e
# opacity=0

[make_all.quantity]
color=0x53585e
# opacity=0

[other_clan.border.inner]
color=0x1b1a18
opacity=255

[other_clan.border.outer]
color=0x1b1a18
opacity=255

[pet_house.border.inner]
color=0x1b1a18
opacity=255

[pet_house.border.outer]
color=0x1b1a18
opacity=255

[poh.build_room.border]
color=0x1b1a18
opacity=255

[portal_nexus.border]
color=0x000000
# opacity=0

[pvp_arena.duel_options.separator]
color=0x000000
# opacity=0

[pvp_arena.confirm_options.separator]
color=0x000000
# opacity=0

[pvp_arena.confirm_options.separator.accent]
color=0x000000
opacity=0

[pvp_arena.recruitment.border.inner]
color=0x000000
# opacity=0

[pvp_arena.recruitment.border.outer]
color=0x1b1a18
opacity=255

[pvp_arena.supplies.separator]
color=0x000000
# opacity=0

[pvp_arena.supplies.stats.border.inner]
color=0x000000
# opacity=0

[pvp_arena.supplies.stats.border.outer]
color=0x1b1a18
opacity=255

[pvp_arena.supplies.kit.equipment.border.inner]
color=0x1c1c1c
opacity=255

[pvp_arena.supplies.kit.equipment.border.outer]
color=0x000000
# opacity=0

[pvp_arena.supplies.kit.list.border.inner]
color=0x1c1c1c
opacity=255

[pvp_arena.supplies.kit.list.border.outer]
color=0x000000
# opacity=0

[pvp_arena.supplies.kit.inventory.border.inner]
color=0x1c1c1c
opacity=255

[pvp_arena.supplies.kit.inventory.border.outer]
color=0x000000
# opacity=0

[pvp_arena.supplies.kit.menu.border.inner]
color=0x181817
opacity=255

[pvp_arena.supplies.kit.menu.border.outer]
color=0x000000
# opacity=0

[pvp_arena.supplies.kit.dropdown.border.inner]
color=0x191818
# opacity=0

[pvp_arena.supplies.kit.dropdown.border.outer]
color=0x000000
# opacity=0

[quest_list.background]
color=0x000000
# opacity=212

[quest_tab.separator]
color=0x000000

[rune_pouch.border.inner]
color=0x1b1a18
opacity=255

[rune_pouch.border.outer]
color=0x1b1a18
opacity=255

[settings_tab.dropdown.border.inner]
color=0x18191a
opacity=255

[settings_tab.dropdown.border.outer]
color=0x000000
# opacity=0

[settings_tab.menu.border.inner]
color=0x18171a
opacity=255

[settings_tab.menu.border.outer]
color=0x000000
# opacity=0

[settings_tab.separator]
color=0x000000

[settings.body.border.inner]
color=0x1c1c1c
opacity=255

[settings.body.border.outer]
color=0x000000
opacity=0

[settings.menu.border.inner]
color=0x1c1c1c
opacity=255

[settings.menu.border.outer]
color=0x000000
opacity=0

[settings.sidebar.border.inner]
color=0x1c1c1c
opacity=255

[settings.sidebar.border.outer]
color=0x000000
opacity=0

[skill_guide.body.border.inner]
color=0x1c1c1c
opacity=255

[skill_guide.body.border.outer]
color=0x000000
opacity=0

[skill_guide.tab.border]
color=0x242424
opacity=255

[soul_wars.separator.bottom]
color=0x1b1a18
opacity=255

[soul_wars.separator.bottom.accent]
color=0x1b1a18
opacity=255

[soul_wars.separator.top]
color=0x1b1a18
opacity=255

[soul_wars.separator.top.accent]
color=0x000000

[spell_tooltip.background]
color=0x002423
opacity=20

[spell_tooltip.border.inner]
color=0x002423
opacity=0

[spell_tooltip.border.outer]
color=0x000000
opacity=0

[toa.applicants.border.inner]
color=0x18171a
opacity=255

[toa.applicants.border.outer]
color=0x000000
# opacity=0

[toa.invocations.border.inner]
color=0x18171a
opacity=255

[toa.invocations.border.outer]
color=0x000000
# opacity=0

[toa.members.border.inner]
color=0x18171a
opacity=255

[toa.members.border.outer]
color=0x000000
# opacity=0

[toa.parties.border.inner]
color=0x18171a
# opacity=0

[toa.parties.border.outer]
color=0x000000
# opacity=0

[toa.summary.border.inner]
color=0x18171a
opacity=255

[toa.summary.border.outer]
color=0x000000
# opacity=0

[toa.separator.bottom]
color=0x1b1a18
opacity=255

[toa.separator.bottom.accent]
color=0x1b1a18
opacity=255

[toa.separator.top]
color=0x1b1a18
opacity=255

[toa.separator.top.accent]
color=0x000000

[tob.applicants.border.inner]
color=0x18171a
# opacity=0

[tob.applicants.border.outer]
color=0x000000
# opacity=0

[tob.parties.border.inner]
color=0x18171a
opacity=255

[tob.parties.border.outer]
color=0x000000
# opacity=0

[tob.party.border.inner]
color=0x18171a
opacity=255

[tob.party.border.outer]
color=0x000000
# opacity=0

[tob.party.header.border.inner]
color=0x18171a
opacity=255

[tob.party.header.border.outer]
color=0x000000
# opacity=0

[world_map.key.border.inner]
color=0x1a1a18
opacity=0

[world_map.key.border.outer]
color=0x000000
opacity=0

[world_map.dropdown.border.inner]
color=0x1b1a18
opacity=0

[world_map.dropdown.border.outer]
color=0x000000
# opacity=0

[world_map.location_menu.border.inner]
color=0x18191a
opacity=255

[world_map.location_menu.border.outer]
color=0x000000
# opacity=0

[world_map.search.border.inner]
color=0x242424
opacity=255

[world_map.search.border.outer]
color=0x000000
# opacity=0

[world_switcher.background]
color=0x000000

[world_switcher.border.bottom]
color=0x000000
# opacity=50

[world_switcher.border.top]
color=0x000000
# opacity=50

[xp_tracker.border.inner]
color=0x002c2b
# opacity=0

[xp_tracker.border.outer]
color=0x001f1f
# opacity=0

[ge.inventory.glow]
color=0x00beb8
# opacity=0

[world_switcher.window.border.inner]
color=0x000000
opacity=0

[world_switcher.window.border.outer]
color=0x18171a
opacity=255

[lms.supplies.border.inner]
color=0x1b1a18
opacity=255

[lms.supplies.border.outer]
color=0x000000
opacity=0

[lms.supplies.dropdown.border.inner]
color=0x1b1a18
opacity=0

[lms.supplies.dropdown.border.outer]
color=0x000000
opacity=0

[lms.supplies.menu.border.inner]
color=0x1b1a18
opacity=255

[lms.supplies.menu.border.outer]
color=0x000000
opacity=0 

[deposit_box.inventory.border.inner]
color=0x1b1a18
opacity=255

[deposit_box.inventory.border.outer]
color=0x000000
opacity=0

[deposit_box.inventory.locked]
color=0x111222
opacity=255

[deposit_lock.border.inner]
color=0x1b1a18
opacity=255

[deposit_lock.border.outer]
color=0x1b1a18
opacity=255

[deposit_lock.hovered.locked]
color=0x8B0000
opacity=0

[deposit_lock.hovered.unlocked]
color=0x959595
opacity=0

[deposit_lock.locked]
color=0x006767
opacity=0

[deposit_lock.unlocked]
color=0x1a1a18
opacity=0

[forestry_shop.reward.hovered]
color=0xb8a182
opacity=0

[forestry_shop.reward.selected]
color=0xff981f
opacity=0

[forestry_shop.reward.unselected]
color=0x726451
opacity=0

[bank.inventory.locked]
color=0x111222
opacity=255

[ge.modify.border]
color=0x1b1a18
opacity=255